"""Add policy, rule, exception, and audit models

Revision ID: 167386b10588
Revises: a7d3bc34b8f8
Create Date: 2026-09-25 05:35:29.196819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '167386b10588'
down_revision: Union[str, None] = 'a7d3bc34b8f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_evidence',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('actor_email', sa.String(length=255), nullable=True),
    sa.Column('policy_id', sa.String(length=36), nullable=True),
    sa.Column('policy_version_id', sa.String(length=36), nullable=True),
    sa.Column('control_run_id', sa.String(length=36), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_evidence_control_run_id'), 'audit_evidence', ['control_run_id'], unique=False)
    op.create_index(op.f('ix_audit_evidence_event_type'), 'audit_evidence', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_evidence_policy_id'), 'audit_evidence', ['policy_id'], unique=False)
    op.create_index(op.f('ix_audit_evidence_timestamp'), 'audit_evidence', ['timestamp'], unique=False)
    op.create_table('policies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('scope', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('policy_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('policy_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('document_name', sa.String(length=255), nullable=False),
    sa.Column('document_path', sa.String(length=500), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('analysis_result', sa.Text(), nullable=True),
    sa.Column('analysis_status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('policy_exceptions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('policy_version_id', sa.String(length=36), nullable=False),
    sa.Column('field', sa.String(length=100), nullable=False),
    sa.Column('operator', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['policy_version_id'], ['policy_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('policy_rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('policy_version_id', sa.String(length=36), nullable=False),
    sa.Column('rule_id', sa.String(length=50), nullable=False),
    sa.Column('rule_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('field', sa.String(length=100), nullable=False),
    sa.Column('operator', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('validation_errors', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['policy_version_id'], ['policy_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('policy_rules')
    op.drop_table('policy_exceptions')
    op.drop_table('policy_versions')
    op.drop_table('policies')
    op.drop_index(op.f('ix_audit_evidence_timestamp'), table_name='audit_evidence')
    op.drop_index(op.f('ix_audit_evidence_policy_id'), table_name='audit_evidence')
    op.drop_index(op.f('ix_audit_evidence_event_type'), table_name='audit_evidence')
    op.drop_index(op.f('ix_audit_evidence_control_run_id'), table_name='audit_evidence')
    op.drop_table('audit_evidence')
    # ### end Alembic commands ###
